Server:
  RunMode: debug
  HttpPort: 8000
  ReadTimeout: 60
  WriteTimeout: 60

App:
  DefaultPageSize: 20
  MaxPageSize: 100
  LogSavePath: storage/logs # fixme
  LogFileName: app
  LogFileExt: .log

Database:
  DBType: mysql
  Username: root # fixme
  Password: root # fixme
  Host: 127.0.0.1:3306 # fixme
  DBName: blog_service
  TablePrefix: blog_
  Charset: utf8
  ParseTime: True
  MaxIdleConns: 10
  MaxOpenConns: 30